---
title: "epistemic caution"
subtitle: |
  
date: "2026-03-29"
draft: true
---

tl;dr: there's a spectrum of how cautious other people when they make inferences about the world
it's very helpful to know where someone else is on this spectrum

the charyness axis
epistemic expansiveness and caution

facetious labels: "epistemic constipation" <-> "epistemic expansiveness"


disciplines:

computer science, psychology, statistics, economics

academics:

philip stark, david freedman, karl rohe (my advisor), computer scientists, ben recht is probably more on the left side of the axis, arun, tyler mccormick on the right side

arguments for both sides of the axis:

caution:
- inference is really hard, and we should do it right, especially when trying to contribute to the body of knowledge of the world
- methods must be mathematically justified

expansiveness:
- push methods boundaries and envelopes is good for the state of methodology (what happens when bad methods disseminate?) proximal inference as arising out of the airoldi confounder adjustment stuff?
- 
- methods can be intuitively justified


science journalists are sort of uncritically summmarizing and rephrasing work

where exactly you end up on this axis is a function of:

- temperament
- training (how can you be cautious if you are not trained to pay attention to epistemic details)
- constraints of your research environment (i.e. psychologists)


kinda a game: where does someone belong on this axis?


medical research conducted by doctors

is epistemic caution related to correctness? where do anti-vaxxers fall on this axis? rejection/acceptence of institutional knowledge and establishments
