---
title: "blog"
listing:
  contents: blog
  sort: "date desc"
  type: default
  categories: true
  fields: [date, title, subtitle, description, reading-time]
page-layout: full
title-block-banner: true
execute: 
  include: false
---

```{r}
# set up some redirects following 
# https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/#netlify-redirects
#
# this relies of netlify deployment

# list names of post folders
posts <- list.dirs(
  path = here::here("blog"),
  full.names = FALSE,
  recursive = FALSE
)

# extract the slugs
slugs <- gsub("^.*_", "", posts)

# lines to insert to a netlify _redirect file
redirects <- paste0("/", slugs, " ", "/blog/", posts)

# write the _redirect file
writeLines(redirects, here::here("_site", "_redirects"))
```

```{r}
library(stringr)

pages <- list.files(
  path = "/dabox/hayes/aleatoric/content",
  recursive = TRUE,
  pattern = ".Rmd"
)

posts <- pages[str_detect(pages, "blog")]

old_slugs <- str_replace(posts, ".Rmd", "")
writeLines(old_slugs, here::here("blog", "old_slugs"))
```
