---
title: "papers"
---
  
I am advised by [Karl Rohe](http://pages.stat.wisc.edu/~karlrohe/) and study community detection in [stochastic blockmodels](../blog/an-annotated-bibliography-on-stochastic-block-models/) and friends using spectral methods. The central idea behind these methods is to estimate parameters in random dot product graphs by estimating their singular subspaces. On the applied side, I've spent a fair amount of time collecting and analyzing portions of the Twitter following graph, and studying effective regularization strategies for networks. I am also currently working with [Keith Levin](https://pages.stat.wisc.edu/~kdlevin/) on network regression.

Outside of network analysis, I'm excited about semi-parametric causal inference, statistical software design, and the foundations of statistics. During my internships at Facebook, I spent some on neural hypergraph embeddings and measuring classifier calibration to predict out-of-sample performance.

You can find my research software on [Github](https://github.com/alexpghayes).

## Publications

1. *Welcome to the Tidyverse.* Hadley Wickham, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D'Agostino McGowan, Romain François, Garrett Grolemund, **Alex Hayes**, Lionel Henry, Jim Hester, Max Kuhn, Thomas Lin Pedersen, Evan Miller, Kirill Müller, David Robinson, Dana Paige Seidel, Vitalie Spinu, Kohske Takahashi, Davis Vaughan, Claus Wilke, Kara Woo, Hiroaki Yutani. 
[Journal of Open Source Software, 2019](https://joss.theoj.org/papers/10.21105/joss.01686)

Last updated on 2022-04-26.




https://scholar.google.com/citations?hl=en&user=6g1T3WIAAAAJ