---
title: "posts"
listing:
  contents: post
  sort: "date desc"
  type: default
  categories: true
  fields: [date, title, subtitle, description, reading-time]
page-layout: full
title-block-banner: true
execute: 
  include: false
---

```{r}
library(stringr)

# set up some redirects following 
# https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/#netlify-redirects
#
# this relies on netlify deployment

# list names of post folders
posts <- list.dirs(
  path = here::here("post"),
  full.names = FALSE,
  recursive = FALSE
)

# extract the slugs
slugs <- gsub("^.*_", "", posts)

# lines to insert to a netlify _redirect file
post_redirects <- glue::glue("/{slugs} /post/{slugs}")

hugo_redirects <- readLines(here::here("post", "hugo_redirects"))

hugo_redirected_to <- hugo_redirects |> 
  str_extract("\\s(.*)") |> 
  str_trim()

# parsing or redirect file failure if there is an NA here
stopifnot(all(!is.na(hugo_redirected_to)))

prepended_posts <- glue::glue("/post/{posts}")
stopifnot(all(hugo_redirected_to %in% prepended_posts))

redirects <- c(post_redirects, hugo_redirects)

# write the _redirect file
writeLines(redirects, here::here("_site", "_redirects"))
```

```{r}
#| eval: false

# quick code to test that everything has been redirected to a place
# that works / doesn't result in a 404 error

library(httr)

urls <- glue::glue("https://www.alexpghayes.com{hugo_redirected_to}")

responses <- purrr::map(urls, GET)
codes <- purrr::map_dbl(responses, status_code)
stopifnot(all(codes == 200))
```

