---
title: "code"
date-modified: "2026-08-19"
bibliography: code.bib
---

At the moment, I primarily develop `R` packages to support research projects -- you can read a little bit about my goals for these packages in [what i want from academic code](../post/what-i-want-from-academic-code/). In brief: I am committed to maintaining and explaining my research code to the extent that it assists others in their own academic research, but I'm not writing research code with the goal of it ending up in production.

Independently from my research, I have been involved in a number of open source projects in the `tidyverse` and `tidymodels` orbits. I previously maintained the [`broom`](https://broom.tidymodels.org/) package, and am responsible for the [`0.5.0` release](https://www.tidyverse.org/blog/2018/07/broom-0-5-0/) and a portion of the [`0.7.0` release](https://www.tidyverse.org/blog/2020/07/broom-0-7-0/). For these contributions I was generously given authorship on @wickham2019.

I review for the [R Journal](https://journal.r-project.org/) and the [Journal of Open Source Software](https://joss.theoj.org/).

You can find all my code on [my GitHub](https://github.com/alexpghayes). Please report bugs and let me know if things break!

## recent news

- 2026-04-16: [`vsp 0.1.4`](https://rohelab.github.io/vsp/) is on CRAN. This update adds several heuristic localization metrics useful for investigating the quality of estimated embeddings.

- 2026-04-15: [`spectralard 0.0.0.9000`](https://github.com/alexpghayes/spectralard) is on GitHub. This in-development package implements estimators for random dot product graphs from Aggregated Relational Data.

## design of statistical software

I was previously quite interested in the design of statistical software and contributed to rOpenSci's [statistical software reviewing guidelines](https://ropensci.org/stat-software-review/), as well as early versions of the [tidymodels implementation principles](https://github.com/tidymodels/model-implementation-principles). I have some long form explorations of modeling software design on my blog:

- [testing statistical software](../post/2019-06-07_testing-statistical-software/)
- [type stable estimation](../post/2019-05-21_type-stable-estimation/)

## research software (in development)

- [`spectralard`](https://github.com/alexpghayes/spectralard) estimates random dot product graphs from Aggregated Relational Data. Functional but lacking documentation.

- [`latentnetmediate`](https://github.com/alexpghayes/latentnetmediate/) estimates natural direct and indirect effects in social network data, using the methods developed in @hayes2025. Methods have been implemented but are not yet documented.

Both of these packages need a small push to land on CRAN. Getting either of these out the door would be a very reasonable undergraduate project.

## research software (released)

- [`fastRG`](https://rohelab.github.io/fastRG/) samples large, sparse random dot product graphs very efficiently and is especially useful when running simulation studies for spectral network estimators. I am committed to maintenance of this package and will respond quickly to feature requests or questions about how you might use it in your own research. The `fastRG` sampling algorithm is described in @rohe2018.

- [`vsp`](https://rohelab.github.io/vsp/) performs semi-parametric estimation of latent factors in random dot product graphs by computing varimax rotations of the spectral embeddings of graphs. The resulting factors are sparse and interpretable. The theory work on this was done by @rohe2023, and then I ended up using varimax rotation a lot in my own data analysis and wrapped some of the infrastructure I developed into this package. I am committed to maintenance of this package and will respond quickly to feature requests or questions about how you might use it in your own research.

- [`fastadi`](https://github.com/RoheLab/fastadi) is a proof-of-concept implementation of `AdaptiveImpute`, a self-tuning matrix completion method with adaptive thresholding that is closely related to `softImpute` [@cho2019; @cho2018]. I extended `AdaptiveImpute` to the computationally challenging case where the entire upper triangle is observed as part of my work with Karl Rohe on citation networks. This is research code rather than code intended for broad consumption. I make no commitments to maintaining or improving this code unless something about it is blocking an ongoing research project.

- [`gdim`](https://CRAN.R-project.org/package=gdim) estimates graph dimension using cross-validated eigenvalues, which determines the number of communities in stochastic blockmodels and variants. The method is described in @chen2021.

- [`aPPR`](https://rohelab.github.io/aPPR/) approximates Personalized PageRanks in large graphs, including those that can only be queried via an API. `aPPR` additionally performs degree correction and regularization, allowing users to recover blocks from stochastic blockmodels [see @chen2020]. Note that the Twitter workflow is defunct: `aPPR` was originally designed to be used together with the [`neocache`](https://github.com/alexpghayes/neocache) backend to sample large portions of the Twitter following graph with high Personalized PageRanks around seed nodes (joint work with [Nathan Kolbow](https://wid.wisc.edu/people/nathan-kolbow/)), but I am no longer maintaining `neocache` and cannot commit any development time to keeping up with the Twitter API shenanigans. [slides](https://github.com/alexpghayes/JSM2021)

## open source work

- [`broom`](https://CRAN.R-project.org/package=broom) converts statistical objects into tidy tibbles, putting hundreds of types of statistical estimates into a consistent format to make programming easier. `broom` is part of the tidyverse; as mentioned above, I no longer maintain the package.

- [`distributions3`](https://CRAN.R-project.org/package=distributions3) provides an S3 interface to distribution functions, with an emphasis on good documentation and beginner friendly design. The vignettes in particular are designed to walk students in intro stat courses through a litany of classic hypothesis tests. [Achim Zeileis](https://www.zeileis.org/) now maintains the package.
