---
title: "getting statistics help"
subtitle: |
  help me help you
date: "2023-10-24"
categories: [statistical software]
draft: true
---

i like consulting

at a very high level: what are you trying to learn (not: how you tried to learn it)

separately: how you tried to learn it

## Summary

- data dictionary
- raw data (what you collected, exactly)
- clean data (what you analyzed, exactly)
- how you made the clean data from the raw data (explaining *why* you did everything you did)
- clean data: 0/1 codes kinda a pain -- use text labels!

spend so much time asking data questions and/or cleaning people's data for them

- show me pictures of your data!







getting stat help

explain the physical meaning of the data (not using any statistical language at all)
explain the scientific question (please do not use any statistical works at all)


"I have some quick stat questions for you"..you sweet sweet summer child. It's probably gonna take me 30-45 minutes to even understand what's going on clearly enough to even understand your question 


