---
title: "talks"
date-modified: "2024-11-01"
---

This page contains material from my past presentations. Many of these presentations are very similar to each other, but I have nonetheless included all the variations on my slides because I find the evolution of presentations (and multiple views on the same problem) to be interesting and informative.

For those of you who prefer skimming slides to reading papers, I've highlighted a few presentations below that are good places to start.

-----

**Estimating peer influence: limitations of linear-in-means models**  
2024-11-22 @ 5 pm, Wisconsin ASA Chapter Meeting  
[poster](https://github.com/alexpghayes/2024-11-12-afi-poster/)

**Estimating peer influence: limitations of linear-in-means models**  
2024-11-12 @ 2:35 pm, American Family Funding Initiative Networking Meeting  
[poster](https://github.com/alexpghayes/2024-11-12-afi-poster/)

::: {.callout-note}
# Summary of my work on network mediation

**Estimating network-mediated causal effects via spectral embeddings**  
2024-06-17 @ 11:45 am, [SINM Satellite](https://sinm.network/sinm2024/), NetSci 2024  
[slides](https://github.com/alexpghayes/2024-06-17-netsci-slides)
:::

::: {.callout-note}
# Summary of my work on colinearity in the linear-in-means model

**Asymptotic identification of peer effects in linear models** (thesis defense)  
2024-04-04 @ 12:30 pm, SMI 133, Medical Sciences Center  
[slides](https://github.com/alexpghayes/2024-04-04-defense-slides)
:::

**Peer effects are parametrically indistinguishable from baseline behaviors in the asymptotic limit**  
2023-11-27 @ 4 pm, Computer Science 1325, Statistics Grad Student Seminar  

**Latent contagion in low-rank networks**  
2023-10-11 @ 2 pm, SMI 133, Levin Lab Meeting  
[slides](https://github.com/alexpghayes/2023-10-11-levin-slides) (private for the time being)

**Peer diffusion over uncertain networks**  
2023-09-18 @ 12:30 pm, WID 1145, [IFDS Ideas Seminar](https://ifds.info/talks/)  
[slides](https://github.com/alexpghayes/2023-09-18-ifds-slides) (private for the time being)

**Estimating network-mediated causal effects via spectral embeddings**  
2023-08-09 @ 10:30 am, *Recent Developments in Causal Inference*, [JSM 2023](https://ww2.amstat.org/meetings/jsm/2023/index.cfm)  
[slides](https://github.com/alexpghayes/2023-08-09-jsm-slides)

**Estimating network-mediated causal effects via spectral embeddings**  
2023-05-24 @ 5:30 pm, Poster Session 1, [ACIC 2023](https://sci-info.org/annual-meeting/)  
[poster](https://github.com/alexpghayes/2023-05-24-acic-poster)

**Estimating network-mediated causal effects via spectral embeddings**  
2023-04-24 @ 12:30 pm, Orchard View @ the WID, [IFDS Ideas Seminar](https://ifds.info/talks/)  
[slides](https://github.com/alexpghayes/2023-04-24-ifds-network-mediation-slides)

**Estimating network-mediated causal effects via spectral embeddings**  
2022-10-14 @ 4:15 pm in MSC 1210, Statistics Graduate Student Association Seminar  
[slides](https://github.com/alexpghayes/2022-10-14-causal-network-regression-slides)

::: {.callout-note}
# Summary of my network mediation work for a spectral networks audience

**Estimating indirect effects induced by homophily via spectral network regression**  
2022-07-07, [Tianxi Li](https://sites.google.com/view/tianxili-homepage/home) and [Can Le](https://statistics.ucdavis.edu/people/can-le) Joint Lab Meeting  
[slides](https://github.com/alexpghayes/2022-07-07-causal-network-regression-slides)
:::

**`distributions3`: From basic probability to probabilistic regression**  
2022-06-23, [UseR 2022](https://user2022.r-project.org/program/talks/#session-34-regression-models)  
[Achim Zeileis](https://www.zeileis.org/), [Moritz Lang](https://moritzlang.org/) and Alex Hayes

The [`distributions3`](https://github.com/alexpghayes/distributions3) package provides a beginner-friendly and lightweight interface to probability distributions. It allows to create distribution objects in the S3 paradigm that are essentially data frames of parameters, for which standard methods are available: e.g., evaluation of the probability density, cumulative distribution, and quantile functions, as well as random samples. It has been designed such that it can be employed in introductory statistics and probability courses. By not only providing objects for a single distribution but also for vectors of distributions, users can transition seamlessly to a representation of probabilistic forecasts from regression models such as GLM (generalized linear models), GAMLSS (generalized additive models for location, scale, and shape), etc. We show how the package can be used both in teaching and in applied statistical modeling, for interpreting fitted models, visualizing their goodness of fit (e.g., via the `topmodels` package), and assessing their performance (e.g., via the `scoringRules` package). [video](https://www.youtube.com/watch?v=rs7ha1F5S0k), [slides](https://www.zeileis.org/papers/useR-2022.pdf)

::: {.callout-note}
# Summary of computational work on Twitter data and an analysis of #rstats Twitter

**The Low Hanging Fruit of the Twitter Following Graph**  
2021-08-11, Joint Statistical Meetings  

In recent applied work on the Twitter media ecosystem, we have found that Twitter metadata (such as follows, likes, quotes, retweets, mentions, etc) is often more informative than the actual content of tweets themselves. The metadata, in some sense, is the right data to use for many inference tasks. In particular, we find that embedding the Twitter following graph is highly informative. However, collecting the following graph is rather challenging due to API rate limits, and storing graphs can also be challenging. We present some computational infrastructure to make access and storage of this high signal data more straightforward, and suggest that research progress would be well served by an increased focus on instrumentation. [slides](https://github.com/alexpghayes/JSM2021)
:::

::: {.callout-note}
# An early, informal presentation about my work on co-factor analysis for citations networks

**A new way to think about citations**  
2020-11-17, Rohe Lab Group Meeting  
[slides](https://github.com/alexpghayes/rohe-lab-citation-impute-slides)
:::

**Solving the model representation problem with broom**  
2019-01-25, `rstudio::conf(2019)`  
[video](https://resources.rstudio.com/rstudio-conf-2019/solving-the-model-representation-problem-with-broom), [slides](https://github.com/alexpghayes/rstudioconf2019-broom-talk)

**Solving the model representation problem with broom**  
2018-11-30, Statistics Graduate Student Seminar  
[slides](https://github.com/alexpghayes/sgsa-seminar-broom-talk)

**Convenient data analysis with broom**  
2018-11-14, RStudio Webinar Series  
[video](https://resources.rstudio.com/webinars/convenient-analysis-with-broom-alex-hayes), [slides](https://github.com/alexpghayes/rstudio-webinar-broom)

**Solving the model representation problem with broom**  
2018-09-19, Madison R User Group  
[slides](https://github.com/alexpghayes/madison-r-user-group-broom-talk)
