---
title: "making sense of academic statistics"
subtitle: |
  some notes on tenure considerations and the relationship between statistics and data analysis
date: "2025-06-23"
bibliography: functionalist-view.bib
draft: true
draft-mode: unlinked
---

Academic statistics can seem counterintuitive and confusing to outsiders, and this post describes why. I describe what the field values and how those incentives shape the kind of work statisticians end up doing—and not doing. My goal is to clarify the sometimes opaque institutional dynamics between academic statistics, data analysis, and the production of scientific knowledge.

I should note that I paint with a broad brush in this post. There's immense variety within academia, and while I hope to capture common patterns, my goal is offer up some stylized facts rather than universal truths.

## incentives in academic statistics

One very natural misconception is that academic statistics is the study of data analysis. This isn't entirely wrong, but it is misleading. Academic statisticians, by and large, are not paid to analyze data, or even to explain how to analyze data. Rather, we are paid to describe how to estimate the parameters of probability models under assumptions that plausibly obtain in the real world. There are other contributions you can make to the statistics literature, but theory work for estimators is canonical. It is the work that most easily understood as a statistical contribution. So academic statisticians are, first and foremost, people who derive theoretical properties of estimators under probability models. 

To be concrete, examples of this kind of work including things like:

- developing novel statistical models and estimators [as in @dunson2009],
- deriving [minimax rates](https://www.stat.cmu.edu/~ryantibs/statml/lectures/minimax.pdf) of convergence and finding minimax estimators or statistical tests [as in @berrett2021a], and
- developing new ways to sample from complicated probability distributions [as in @neal2003],

amongst others^[See @gelman2020 for a short review of important recent ideas in statistics and @efron2021 for a textbook-length treatment of influential methods.].

This emphasis on theoretical and methodological work has some surprising consequences. The first is that academic statistics has an ambivalent relationship to data analysis, by which I mean that we don't necessarily analyze very much data in our research or in our training. Over the years, there have been numerous calls within the discipline to engage with data analysis more seriously. For instance, nearly 80 years ago Tukey took great care to describe himself as a data analyst first, and a statistician second, and to plead with statisticians to contribute more to data analysis [@tukey1962]. @breiman2001 similarly lambasted statisticians for studying models with little practical relevance. Despite these calls, at tenure time, one of the best things you can do is have an *Annals of Statistics* paper on your CV, which is about as theoretical as it gets.

In statistics graduate programs, the emphasis on mathematical statistics over data analysis is clear, with coursework covering primarily probability, linear algebra and analysis. Most graduate programs in statistics do include a sequence on regression and experimental design, but emphasize derivation of $F$-tests and textbook data examples over, say, data cleaning. Indeed, the fact that statisticians routinely distinguish between "real-world data" and "toy data" is telling. Most graduate programs also include a course on statistical consulting. For some graduate students, an exclusively theoretical dissertation means that this consulting course is their only experience working with data, since writing theory papers simply requires different skills than doing data analysis^[Perhaps as a consequence, applied statisticians often describe a rule of thumb is that you aren't capable of doing meaningful applied work until you've been working in and learning about a particular domain for at least three years.]. The end result is that some graduate students are unpracticed with data analysis when they earn their degrees.

## data analysis by statisticians

When statisticians do work with data, it's usually in one of two ways: as data examples to illustrate how an estimator works, or a complicated standalone data analysis. Crucially, the point of data applications is to help readers understand the method, not the data or the world^[Two representative examples of data applications in my own sub-field are @qing2022 and @chen2020. @qing2022 develops a new network formation model and shows it fits better data better than an older model. There is not really scientific inference on the data itself in the paper. @chen2020 develops a new method for locally clustering social networks, and then applies that method to Twitter data, and it's certainly interesting, but the data analysis is not in support of any claims about how the world fundamentally works.]. One plus side of this methodological focus is that statisticians are much less beholden to reviewers wanting p-values below 0.05 or splashy results. Rather, our data applications are evaluated on the correctness of the methodological application, with some indifference to scientific conclusions. This is really, really nice, and I do not envy publication pressures in more scientific fields.

Data analysis can also sometimes end up in statistics journals. Typically, this happens when there is a complicated dataset and someone comes up with a method specifically to analyze that data. For instance, my own paper @hayes2025a does some methods work, but it's all in the service of analyzing one very specific dataset. To get this type of work published, the analysis needs to be new or interesting or impactful or just very complicated. Biostatistics departments tend to be more applied than statistics departments, and have a lot more high impact data, and so they to do more of this kind of work.

When statisticians do careful analyses on interesting data without statistically novel elements, these papers *do not end up in statistics journals*. They end up in scientific or social scientific journals, and in a lot of departments, the tenure payoff is not proportional to the labor it takes to actually do good science. This ambivalence towards data analysis can be [frustrating](https://x.com/pli_cachete/status/1836042146505244807) to people trying to do science or learn about the world.

<!-- > As someone who has spent good entire adult life in academic statistics departments I can say with certainty that we have lost the Mandate of Heaven. I would certainly prefer hiring someone trained as an economist or a political scientist if my goal was finding truth from data https://x.com/pli_cachete/status/1836042146505244807 -->

<!-- {{< tweet user=pli_cachete id=1836042146505244807 >}} -->

## service

Earlier I mentioned that the graduate curriculum in statistics prioritizes mathematical statistics over data analysis. So what happens in service courses designed for students in different departments, do those classes teach data analysis skills? My impression is that many service courses retain the heavy mathematical emphasis of courses designed for statistics students. Most service courses I've seen focus heavily on hypothesis testing and linear regression, with some limited programming instruction. It's a start, but no matter how you slice it, it's just not enough instruction to produce the level of applied competence that most scientific disciplines expect from their students. I often see graduate students go into these courses expecting to learn everything they need to know to analyze data, and then emerging later surprised and frustrated. Some explicit expectation setting might smooth out this experience.

The fact that service courses are not always sufficiently tailored to applied audiences comes up on occasion. A [notable episode](https://x.com/siminevazire/status/1144941216259354625) from several years back on Twitter involved a prominent psychologist making the claim that psychologists could teach data analysis better than statisticians. While I don't fully agree, I think it's valuable to consider how statistics courses are largely designed to train future tenured statistics faculty, and this is the wrong kind of training for scientists. Statisticians largely produce methods. Scientists largely produce knowledge about the world.

Another consequence of the methodological focus is that statisticians sometimes produce tools that are not particularly useful, since we are not always consumers of our own methods. This can also be the source of some [frustration and  confusion](https://x.com/Apoorva__Lal/status/1836149850444021978). The issue is not malice so much as prioritization. Actual science is just not on our critical path all that often. Because of this, statisticians are at risk of solving the wrong problem (i.e., a tractable mathematical problem rather than a scientific important one), or communicating insufficiently how our tools work, or never implementing our methods in usable software, or just generally developing a method so complicated that the effort to learn the method is not worthwhile^[I have heard some complaints that econometrics is increasingly taking a turn in this direction.].

## how other fields have responded

Since statisticians don't really do service work, what tends to happen is that many applied departments, especially in the social sciences, will hire a small number of methodologists with a mixture of statistical and domain background. These methodologists teach statistics courses to graduate students in their own departments and do lots of translational labor, turning esoteric theory papers into tutorials and software. On one hand, this is a rational response to statistical indifference. On the other hand, the quality of work done by quantitative methodologists outside of statisticians is variable, so statisticians are not always particularly supportive of this approach.

An especially ironic consequence is that statisticians have more limited influence on the practice of data analysis than we might hope. This can be disheartening as a statistician, because we would very much like to be seen as and treated like experts. Which, notably, we are. It's very easy to feel jaded about this, because a substantial amount of data analysis in science contains methodological errors that result in incorrect inferences. A decent chunk is sloppy but redeemable, and another portion is done very well^[Methodologists are on the end of a weird and limited inversion of Brandolini's law, where it is far easier to recognize a bad data analysis than it is to produce a good one. There is a common adage that data science is the intersection of statistical expertise, data manipulation skills, and domain expertise, and that you need all three of these skills to analyze data well. To identify serious flaws is a data analysis, statistical expertise alone suffices.]. 

So when academic statistics is in fact interested the practice of statistics, we are often hamstrung by the fact that we are an insular institution, and that we have rarely spent time developing cultural capital. In a sense, statistics is in a state of crisis, on the verge of irrelevance. In another sense, the actual practice of statistics by scientists makes it clear that there is no real risk of irrelevance. 

## a summary in stylized facts

To sketch out the story all at once, I think a reasonable summary goes along these lines: statisticians respond strongly to tenure incentives, which pulls us strongly in a theoretical rather than applied direction. Consequently, academic statistics has largely opted out of service responsibilities to other disciplines. It's not that we don't do service, but that our service isn't as helpful as others would hope. As a result, statistics can be seen as aloof or apathetic or indifferent (c.f. computer science, economics). Other disciplines have responded by building in-house statistical capacity of variable quality, and by ignoring statistics proper to some extent. This makes sense because a lot of statistics isn't useful to scientists for various reasons. It's also concerning because a lot of data analysis by scientists needs improvement. Frustrations abound on all sides because scientists want help with their data analysis and statisticians want people to analyze data well and also want to be taken seriously.

I should temper the sketch above with the note that most statisticians I know genuinely want to develop and teach useful methods, most scientists I know genuinely want to do good science, and science and statistics are enterprises that have made enormous progress over the last decades.

That said, it feels to me like a reasonable time to contemplate how statistics wants to relate to other fields. Are we interested in the technical problem of producing a rich statistical literature, or the social problem of producing a rich practice of statistics? Do our tenure practices reflect these priorities? 

I don't think there are necessarily right or wrong choices, but there are certainly tradeoffs. My view is that statistics currently prioritizes a rich statistical literature, and the cost of this is that we have a less rich statistical practice in the sciences^[What would statistics look like if tenure packets were evaluated for tutorial papers, for scientific contributions, for code, for outreach work?]. Regardless of our precise priorities, I think it is important to articulate our values and to explain them to others, so that outsiders can understand what is on offer and what is not. Some sets of priorities may lead to conflicts that are difficult to resolve. There's tension between pointing out methodological problems and actually helping people fix them.

My hope is that this tension, and some others, make more sense than they did at the beginning of the post. Tenure in statistics is about methods and theory work, and as a consequent statisticians often de-prioritize data analysis and scientific contribution. That said, things may be changing. Statistics departments grew substantially during the data science boom, and the field feels invigorated with new people and new ideas and new priorities. I'm curious to see where we head next.

#### acknowledgements

I would like to thank [Ben Listyg](https://github.com/benlistyg) for helpful comments on this post. Ben is consistently a sounding board for my half-formed ideas, and I am immensely grateful.

<!-- Cognitive limits, scaffolds, familiarity/super users as dramatically misjudging the depth of their schema/scaffolds, at least in math. Why shared understanding is hard. Why XXXXX is hard to work with. Why I myself am hard to work with on projects outside of my expertise -->

<!-- Another thing I have been thinking about recently: it surprises me that statistics departments do not offer classes that require little scaffolding. A stat 101 course on critical thinking/quantitative reasoning, along the lines of Art of Statistics or calling bullshit; i.e. a class design for people who are exclusively going to consume, but never produce, statistics, and who don't know any math. this would be a super valuable thing for us to do and for some reason we do not. -->



<!-- the replications crisis people were like "the house is on fire, look at all these questionable research practices and outright fraud" in fields where, from a statistical viewpoint, there is no need to distinguish between fraudulent work and non-fraudulent work because the quality is often indistinguishable. also, it's been clear that the house has been on fire to outsiders for years, so the loud yelling all of a sudden is a bit irritating. -->


<!-- 

other fields to comment on:
- psychology
- econometrics
- computer science
- applied math & engineering


## Collaboration does not solve the misaligned incentives problem

- doesn't super work to develop methods -- shared understanding hard to develop with social scientists missing years of training (hourly rates meme)
- outsourcing data analysis can work, but then once again in the misaligned incentives category


some interdisciplinary collaborations are great. that said, past experiences lead me to be extremely hesitant to collaborate on methodology -- outsource your problem to me and i solve it independently

 Some weird dynamics when collaborating across disciplinary boundaries

seems to work best when data analysis is fully outsourced
joint methods development has, so far i can tell, mostly been a disaster

really hard to get to shared understanding of the project

- maybe you want help analyzing your data, and you do reach out to a statistican, at which point you discover: they maybe think your whole field is non-sense, they are maybe a grumpy methodologist, and they aren't incentivized to publish with you, so your collaboration is going to be a low priority for them. even if they are super excited to do data analytic work with you, pre-tenure folks are still going to be subject to incentives that are not in favor of collaboration.

near-universal adage that working with statisticians is a royal pain in the ass. slow. unenthused, etc.

Here's a rough model of how things actually work:

statistics culture: somewhat nitpicky, apathetic towards other, and not particularly charismatic. sociologically outcompeted at every turn by computer scientists, who build impressive large systems that kick ass at prediction, who have money, who are charisma, and tend not to sweat the inferential details, actually market their work, etc, etc

- joint methods development with social scientists is often quite painful. hourly rates meme
- what passes muster in social sciences is desk reject worthy in statistics
- i have been involved in 2-3 collaborative projects where i bowed out because the methodological content of the projects would have been embarrassing and potentially detrimental to my career to attach my name to. weird weird dynamics here when getting paid to help a social scientist with a thing.

Advice for people who need statistical help:
- pay statisticians
- do a transactional data analysis for authorship trade
- make sure the statistician understands the scientific question
 -->
